services:
  barracuda-dvl:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    container_name: barracuda-dvl
    tty: true
    network_mode: host
    restart: "no"
    volumes:
      - $HOME/.gitconfig:/root/.gitconfig:ro
      - $HOME/.ssh:/root/.ssh
    working_dir: /opt/barracuda-dvl

